export default function getProviderList(req, res) {
  if (
    req.method === "GET" &&
    req.query.patientId !== "2e73ad0d-c959-4130-ab3b-fcdd5cb10505"
  ) {
    res.status(200).json({
      results: [
        {
          designation: "MBBS, MD",
          firstName: "Jaco",
          lastName: "David",
          nickName: "Jaco",
          employeeNumber: "755708",
          mi: "Jaco",
          dob: "02/07/1971",
          email: "eyecare@gmail.com",
          sex: {
            key: 11,
            name: "M",
            order: 1,
            notes: "",
          },
          available: true,
          note: "Test",
          age: "51",
          address: {
            addressLine1: "568 Allens Mill Rd",
            city: "Yorktown",
            state: "VA",
            zip: "23692",
          },
          homePhone: "4981261115",
          cellPhone: "2812942993",
          inHouse: false,
          providerDetails: {
            isProvider: true,
            isExternalProvider: false,
            materialRate: "0",
            drFirstCredentialDetails: {
              drFirstCredential: false,
              username: "",
              password: "",
              signature: "",
            },
            npi: "1134296023",
            professionalEq: "1234",
            opticalEq: "12",
            surgicalEq: "344",
            contactEq: "12346",
            provider: "",
            onlineProvider: true,
            license: [],
            deaIds: [],
            taxonomyCode: "207ND0101X",
            classification: "Dermatology",
            specialization: "MOHS-Micrographic Surgery",
            rating: 9,
            language1: "Arabic",
            language2: "Chinese",
            language3: "German",
            profilePhoto: {
              digitalAsset: {
                uid: "d72b0b16-99ab-4ae4-aba3-13b81930b68a",
                fileName: "test",
                assetUrl: "/v1/patient",
                _version: "d72b0b16-99ab-4ae4-aba3-13b81930b77a",
              },
            },
          },
          offices: [
            {
              name: "Ballwin",
              addressLine1: "568 Allens Mill Rd",
              city: "Yorktown",
              state: "VA",
              zip: "23692",
              _id: "4cd970a0-8529-4b44-a4c5-99c9f4e8d078",
            },
            {
              name: "Edwardsville ",
              addressLine1: "700 12th St # A",
              city: "Bellingham",
              state: "WA",
              zip: "98225",
              _id: "cd68948d-aa9d-4100-a806-1afd2b227104",
            },
          ],
          status: "UPDATED",
          managerialAdjustments: false,
          overrideExpiredPromo: false,
          sources: [],
          _links: {
            self: {
              href: "/v1/employees/b579b0d1-0c93-4db4-8ca8-294a60e718e4",
            },
          },
          _id: "b579b0d1-0c93-4db4-8ca8-294a60e718e4",
        },
        {
          designation: "MBBS, MD",
          firstName: "Jaco",
          lastName: "David",
          nickName: "Jaco",
          employeeNumber: "755708",
          mi: "Jaco",
          dob: "02/07/1971",
          email: "eyecare@gmail.com",
          sex: {
            key: 11,
            name: "M",
            order: 1,
            notes: "",
          },
          available: true,
          note: "Test",
          age: "51",
          address: {
            addressLine1: "568 Allens Mill Rd",
            city: "Yorktown",
            state: "VA",
            zip: "23692",
          },
          homePhone: "4981261115",
          cellPhone: "2812942993",
          inHouse: false,
          providerDetails: {
            isProvider: true,
            isExternalProvider: false,
            materialRate: "0",
            drFirstCredentialDetails: {
              drFirstCredential: false,
              username: "",
              password: "",
              signature: "",
            },
            npi: "1134296023",
            professionalEq: "1234",
            opticalEq: "12",
            surgicalEq: "344",
            contactEq: "12346",
            provider: "",
            onlineProvider: true,
            license: [],
            deaIds: [],
            taxonomyCode: "207ND0101X",
            classification: "Dermatology",
            specialization: "MOHS-Micrographic Surgery",
            rating: 9,
            language1: "Arabic",
            language2: "Chinese",
            language3: "German",
            profilePhoto: {
              digitalAsset: {
                uid: "d72b0b16-99ab-4ae4-aba3-13b81930b68a",
                fileName: "test",
                assetUrl: "/v1/patient",
                _version: "d72b0b16-99ab-4ae4-aba3-13b81930b77a",
              },
            },
          },
          offices: [
            {
              name: "Ballwin",
              addressLine2: "568 Allens Mill Rd",
              _id: "4cd970a0-8529-4b44-a4c5-99c9f4e8d078",
            },
            {
              name: "Edwardsville ",
              addressLine1: "700 12th St # A",
              city: "Bellingham",
              state: "WA",
              zip: "98225",
              _id: "cd68948d-aa9d-4100-a806-1afd2b227104",
            },
          ],
          status: "UPDATED",
          managerialAdjustments: false,
          overrideExpiredPromo: false,
          sources: [],
          _links: {
            self: {
              href: "/v1/employees/b579b0d1-0c93-4db4-8ca8-294a60e718e4",
            },
          },
          _id: "b579b0d1-0c93-4db4-8ca8-294a60e718e4",
        },
        {
          designation: "MBBS, MD",
          firstName: "Jaco",
          lastName: "David",
          nickName: "Jaco",
          employeeNumber: "755708",
          mi: "Jaco",
          dob: "02/07/1971",
          email: "eyecare@gmail.com",
          sex: {
            key: 11,
            name: "M",
            order: 1,
            notes: "",
          },
          available: true,
          note: "Test",
          age: "51",
          address: {
            addressLine1: "568 Allens Mill Rd",
            city: "Yorktown",
            state: "VA",
            zip: "23692",
          },
          homePhone: "4981261115",
          cellPhone: "2812942993",
          workPhone: "2812942993",
          inHouse: false,
          providerDetails: {
            isProvider: true,
            isExternalProvider: false,
            materialRate: "0",
            drFirstCredentialDetails: {
              drFirstCredential: false,
              username: "",
              password: "",
              signature: "",
            },
            npi: "1134296023",
            professionalEq: "1234",
            opticalEq: "12",
            surgicalEq: "344",
            contactEq: "12346",
            provider: "",
            onlineProvider: true,
            license: [],
            deaIds: [],
            taxonomyCode: "207ND0101X",
            classification: "Dermatology",
            specialization: "MOHS-Micrographic Surgery",
            rating: 9,
            language1: "Arabic",
            language2: "Chinese",
            language3: "German",
            profilePhoto: {
              digitalAsset: {
                uid: "1ffaf737-57ac-4660-8a32-f0650e2285ae",
                fileName: "test",
                assetUrl: "/v1/patient",
                _version: "d72b0b16-99ab-4ae4-aba3-13b81930b77a",
              },
            },
          },
          offices: [
            {
              name: "Ballwin",
              addressLine1: "568 Allens Mill Rd",
              city: "Yorktown",
              state: "VA",
              zip: "23692",
              _id: "4cd970a0-8529-4b44-a4c5-99c9f4e8d078",
            },
            {
              name: "Edwardsville ",
              addressLine1: "700 12th St # A",
              city: "Bellingham",
              state: "WA",
              zip: "98225",
              _id: "cd68948d-aa9d-4100-a806-1afd2b227104",
            },
          ],
          status: "UPDATED",
          managerialAdjustments: false,
          overrideExpiredPromo: false,
          sources: [],
          _links: {
            self: {
              href: "/v1/employees/b579b0d1-0c93-4db4-8ca8-294a60e718e4",
            },
          },
          _id: "b579b0d1-0c93-4db4-8ca8-294a60e718e4",
        },
      ],
    });
  } else {
    res.status(200).json({
      results: [],
    });
  }
}
