apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: patient
  name: patient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: patient
    spec:
      containers:
      - image: 056640875000.dkr.ecr.us-east-1.amazonaws.com/photon-ecp-e360-dev:ecp-patient-TAG
        name: patient
        imagePullPolicy: Always
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: patient
  name: patient
    annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"

spec:
  ports:
  - name: 80-3000
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: patient
  type: LoadBalancer
status:
  loadBalancer: {}
