module.exports = {
  EMPTY_STRING: "",
  H1: "h1",
  H2: "h2",
  SMALL: "small",
  LARGE: "large",
  PATIENT: "patient",
  PRIMARY: "primary",
  SECONDARY: "secondary",
  MIDDLE: "middle",
  CENTER: "center",
  FLEX_END: "flex-end",
  BODY_REGULAR: "bodyRegular",
  FILLED: "filled",
  INPUT_TEXT: "text",
  INPUT_PASSWORD: "password",
  ACCOUNT_LOCK_COUNT: 3,
  SUBMIT: "submit",
  SELECT_OPTION: "selectOption",
  SECURITY_QUESTION: "securityQuestion",
  ONE_TIME_LINK: "oneTimeLink",
  PASSWORD_RESET: "passwordReset",
  BOTH: "both",
  MODE_COMMUNICATION_KEY: "modeComunication",
  EMAIL: "email",
  PHONE: "phone",
  YES: "yes",
  MFA_COMPONENT_NAME: "MultiFactorAuthentication",
  SQ_COMPONENT_NAME: "SecurityQuestion",
  MONTH_NAME: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ],
  TEST_ID: {
    LOGIN_TEST_ID: {
      email: "emailorphonenumber",
      password: "password",
      forgotLink: "forgotpswd",
      loginBtn: "loginbtn",
      guestBtn: "continueasguest",
      createAccountBtn: "createaccount",
    },
    FORGOT_TEST_ID: {
      email: "emailorphonenumber",
      continueBtn: "continuebtn",
      loginLink: "backtologin",
      answerQuestions: "answerquestions",
      oneTimeLink: "onetimelink",
      securityQuestion: "securityquestion",
    },
    REGISTER_TEST_ID: {
      firstname: "firstname",
      lastname: "lastname",
      dateofbirth: "dateofbirth",
      calander: "calander",
      email: "email",
      mobilenumber: "mobilenumber",
      password: "password",
      emailradio: "emailradio",
      phoneradio: "phoneradio",
      bothradio: "bothradio",
      registerbtn: "registerBtn",
      loginlink: "loginlink",
    },
    HOME_TEST_ID: {
      appoinments: "appoinments",
      myhealthchart: "myhealthchart",
      mycareteam: "mycareteam",
      labresults: "labresults",
      billing: "billing",
      username: "username",
      account: "account",
      logout: "logout",
    },
    APPOINTMENT_TEST_ID: {
      location: "location",
      searchbtn: "searchbtn",
      filterbtn: "filterbtn",
      locationInput: "locationInput",
      dateInput: "dateInput",
      purposeInput: "purposeInput",
      insuranceInput: "insuranceInput",
    },
    BIOGRAPHY_TEST_ID: {
      about: "biography-about",
      location: "biography-location",
      insurance: "biography-insurance",
      education: "biography-education",
      viewAll: "biography-view-all-insurance",
    },
    INSURANCE_TEST_ID: {
      addButton: "loc_btnAddInsurance",
      provider: "loc_inputProvider",
      planName: "loc_inputPlan",
      subscriberId: "loc_inputSubsId",
      group: "loc_inputGroup",
      save: "loc_btnSaveInsuranve",
      cancel: "loc_btnCancelInsuranve",
      uploadFrontImage: "loc_btnUploadFront",
      uploadBackImage: "loc_btnUploadBack",
    },
  },
};
