module.exports = {
    EMPTY_STRING:"",
    H1:"h1",
    H2:"h2",
    SMALL:"small",
    LARGE:"large",
    PATIENT:"patient",
    PRIMARY:"primary",
    SECONDARY:"secondary",
    MIDDLE:"middle",
    CENTER:"center",
    FLEX_END:"flex-end",
    BODY_REGULAR:"bodyRegular",
    FILLED:"filled",
    INPUT_TEXT:"text",
    INPUT_PASSWORD:"password",
    ACCOUNT_LOCK_COUNT: 3,
    SUBMIT:"submit",
    SET_OPTION:"setOption",
    SECURITY_QUESTION:"securityQuestion",
    ONE_TIME_LINK:"oneTimeLink",
    PASSWORD_RESET: "passwordReset",
    BOTH:"both",
    MODE_COMMUNICATION_KEY:"modeComunication",
    EMAIL:"email",
    PHONE:"phone",
}