module.exports = {
  EMPTY_STRING: "",
  H1: "h1",
  H2: "h2",
  SMALL: "small",
  LARGE: "large",
  PATIENT: "patient",
  PRIMARY: "primary",
  SECONDARY: "secondary",
  MIDDLE: "middle",
  CENTER: "center",
  FLEX_END: "flex-end",
  BODY_REGULAR: "bodyRegular",
  FILLED: "filled",
  INPUT_TEXT: "text",
  INPUT_PASSWORD: "password",
  ACCOUNT_LOCK_COUNT: 3,
  SUBMIT: "submit",
  SELECT_OPTION: "selectOption",
  SECURITY_QUESTION: "securityQuestion",
  ONE_TIME_LINK: "oneTimeLink",
  PASSWORD_RESET: "passwordReset",
  BOTH: "both",
  MODE_COMMUNICATION_KEY: "modeComunication",
  EMAIL: "email",
  PHONE: "phone",
  YES: "yes",
  MFA_COMPONENT_NAME: "MultiFactorAuthentication",
  SQ_COMPONENT_NAME: "SecurityQuestion",
  MONTH_NAME: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ],
  DAY_NAME: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  TEST_ID: {
    LOGIN_TEST_ID: {
      email: "emailorphonenumber",
      passwordField: "password",
      forgotLink: "forgotpswd",
      loginBtn: "loginbtn",
      guestBtn: "continueasguest",
      createAccountBtn: "createaccount",
      syncAppointmentLink: "syncAppointmentLink",
    },
    FORGOT_TEST_ID: {
      email: "emailorphonenumber",
      continueBtn: "continuebtn",
      loginLink: "backtologin",
      answerQuestions: "answerquestions",
      oneTimeLink: "onetimelink",
      securityQuestion: "securityquestion",
    },
    REGISTER_TEST_ID: {
      firstname: "firstname",
      lastname: "lastname",
      dateofbirth: "dateofbirth",
      calander: "calander",
      email: "email",
      mobilenumber: "mobilenumber",
      passwordField: "password",
      emailradio: "emailradio",
      phoneradio: "phoneradio",
      bothradio: "bothradio",
      registerbtn: "registerBtn",
      loginlink: "loginlink",
    },
    SCHEDULE_GUEST_TEST_ID: {
      firstname: "firstname",
      lastname: "lastname",
      dateofbirth: "dateofbirth",
      calander: "calander",
      email: "email",
      mobilenumber: "mobilenumber",
      passwordField: "password",
      emailradio: "emailradio",
      phoneradio: "phoneradio",
      bothradio: "bothradio",
      registerbtn: "registerBtn",
      signInlink: "signInlink",
    },
    CANCEL_SCHEDULE_TEST_ID: {
      btnCancel: "loc_btnCancel",
      btnKeep: "loc_btnKeep",
      other: "other",
    },
    HOME_TEST_ID: {
      appoinments: "appoinments",
      myhealthchart: "myhealthchart",
      mycareteam: "mycareteam",
      labresults: "labresults",
      billing: "billing",
      username: "username",
      account: "account",
      logout: "logout",
      header: {
        index: "header",
        logo: "header_logo",
        userAvatar: "user_avatar",
      },
    },
    MFA_TEST_ID: {
      radioEmail: "loc_RadioEmail",
      radioPhone: "loc_RadioPhone",
      rememberMe: "loc_chkRemember",
      btnConfirm: "loc_btnConfirm",
      btnBack: "loc_btnBack",
      inputCode: "loc_txtEnterCode",
      btnSubmit: "loc_btnSubmit",
      btnResend: "loc_btnResend",
      btnSubmitSecurity: "loc_btnSubmitSecurity",
      btnSkip: "loc_btnSkip",
    },
    PERSONAL_INFO_TEST_ID: {
      txtName: "loc_txtName",
      btnSave: "loc_btnSave",
      btnCancel: "loc_btnCancel",
      btnDelete: "loc_btnDelete",
    },
    APPOINTMENT_TEST_ID: {
      location: "location",
      searchbtn: "searchbtn",
      searchSlotbtn: "searchAvailableSlot",
      filterbtn: "filterbtn",
      locationInput: "locationInput",
      dateInput: "dateInput",
      purposeInput: "purposeInput",
      insuranceInput: "insuranceInput",
      DIALOG_VIEW_ALL: {
        container: "dialogViewAll",
        scheduleContainer: "appointment_all_availability_schedule_ontainer",
        previousWeekButton: "appointment_all_availability_previous_week_button",
        nextWeekButton: "appointment_all_availability_next_week_button",
        timeslotButton: "appointment_all_availability_timeslot_button",
      },
      PROVIDER_PROFILE: {
        image: "appointment_provider_profile_image",
        name: "appointment_provider_profile_name",
      },
      FILTER_RESULT: {
        container: "appointment_filter_result_container",
      },
      FILTER_COMPONENT: {
        drawer: "appointment_filter_component_drawer",
      },
    },
    BIOGRAPHY_TEST_ID: {
      about: "biography-about",
      location: "biography-location",
      insurance: "biography-insurance",
      education: "biography-education",
      viewAll: "biography-view-all-insurance",
    },
    INSURANCE_TEST_ID: {
      addButton: "loc_btnAddInsurance",
      provider: "loc_inputProvider",
      planName: "loc_inputPlan",
      subscriberId: "loc_inputSubsId",
      group: "loc_inputGroup",
      save: "loc_btnSaveInsuranve",
      cancel: "loc_btnCancelInsuranve",
      uploadFrontImage: "loc_btnUploadFront",
      uploadBackImage: "loc_btnUploadBack",
    },
    SEARCH_PROVIDER_TEST_ID: {
      viewAll: "loc_viewAll",
      hourButton: "loc_hourButton",
    },
    SUBNAVIGATION: "subNavigation-link",
    SCHEDULE_APPOINTMENT_TEST_ID: {
      APPOINTMENT_LOCATION: {
        editButton: "schedule_appointment_location_edit_button",
        address: "schedule_appointment_location_address",
      },
      APPOINTMENT_DETAILS: {
        editButton: "schedule_appointment_details_edit_button",
        date: "schedule_appointment_location_date",
      },
      step2Button: "schedule_appointment_step2_button",
      DIALOG_CONFIRMATION_RESCHEDULE: {
        confirmBtn: "schedule_appointment_dialog_reschedule_confirm_button",
        denyBtn: "schedule_appointment_dialog_reschedule_deny_button",
      },
      MAPS: {
        pinMarker: "schedule_appointment_maps_pin_marker",
        infoWindow: {
          timeslot: "schedule_appointment_maps_info_window_timeslot",
        },
      },
    },
    APPOINTMENTS_TEST_ID: {
      upcomingAppointmentsHeader: "appointments_upcoming_appointments_header",
      cancelAppointmentButton:
        "appointments_upcoming_appointments_cancel_button",
      rescheduleAppointmentButton:
        "appointments_upcoming_appointments_reschedule_button",
      confirmRescheduleButton:
        "appointments_upcoming_appointments_confirm_reschedule_button",
    },
    MAP_INFO_WINDOW: {
      previousProvider: "provider_btnPrevious",
      nextProvider: "provider_btnNext",
    },
    APPOINTMENTS_DETAIL_TEST_ID: {
      expandCollapseAll: "appointment_expandCollapseAll",
      expandCollapseSection: "provider_expandCollapseSection",
      download: "provider_btnDownload",
    },
    MEDICAL_RECORD: {
      moreMenu: "medical_more_menu",
    },
  },
  ERROR_CODE: {
    NETWORK_ERR: "ERR_NETWORK",
    BAD_REQUEST: "ERR_BAD_REQUEST",
  },
  DOCUMENT_STATUS: "RESULTS_AVAILABLE",
};
